# Generated by Django 6.0.2 on 2026-02-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('sqlite', 'SQLite'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongo', 'MongoDB')], default='sqlite', max_length=20)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('differential', 'Differential')], default='full', max_length=20)),
                ('connection_params', models.JSONField(blank=True, default=dict)),
                ('storage_type', models.CharField(default='local', max_length=20)),
                ('destination', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_compressed', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('storage_type', models.CharField(default='local', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('is_compressed', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='backup_core.backupjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_params', models.JSONField(blank=True, default=dict)),
                ('selected_tables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_jobs', to='backup_core.backupartifact')),
                ('backup_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_jobs', to='backup_core.backupjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='backup_core.backupjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
