# Generated by Django 6.0.2 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="max_retries",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="schedule",
            name="retry_backoff_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="schedule",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
